Website/Controllers/NotesController.cs
using Core.Domains;

using Data.DTOs;
using Data.Migrations;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Pal.Web.Extensions;

using Service;

namespace Website.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly INotesService _notesService;

        public NotesController(INotesService notesService)
        {
            _notesService = notesService;
        }


        public async Task<IActionResult> Index()
        {
            var notesResult = await _notesService.GetNotesAsync();
            if (notesResult.IsSuccess)
            {
                return View(notesResult.Data);
            }

            return View();
        }

        [ServiceFilter(typeof(CheckUserAttribute))]
        public async Task<IActionResult> Manage(int? id)
        {
            if (id.HasValue)
            {
                var noteResult = await _notesService.GetNoteAsync(id.Value);
                if (noteResult.IsSuccess)
                {
                    return View(noteResult.Data);
                }
                else
                {
                    return RedirectToAction("Index"); //TODO: Show Error
                }

            }

            return View(new NoteDTO());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Manage(NoteDTO model)
        {

            if (ModelState.IsValid)
            {
                ResponseResult result;
                if (model.Id == 0) //Add
                {
                    result = await _notesService.AddNote(model);
                    if (result.IsSuccess)
                    {
                        return RedirectToAction("Index");
                    }
                }
                else //Update
                {
                    result = await _notesService.UpdateNoteAsync(model);
                    if (result.IsSuccess)
                    {
                        return RedirectToAction("Index");
                    }
                }

                ModelState.AddModelError("", result.Errors.FirstOrDefault());
            }

            return View("Add", model);

        }


        [HttpPost]
        [ServiceFilter(typeof(CheckUserAttribute))]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _notesService.DeleteNoteAsync(id);
            return Json(result);
        }


        [HttpPost]
        [ServiceFilter(typeof(CheckUserAttribute))]
        public async Task<IActionResult> Share(int id, string shareLink)
        {
            var result = await _notesService.ShareNoteAsync(id, shareLink);
            return Json(result);
        }

        [AllowAnonymous]
        //[Route("Note/{shareLink}")]
        public async Task<IActionResult> Shared(string shareLink)
        {
            var noteResult = await _notesService.GetSharedNoteAsync(shareLink);
            if (noteResult.IsSuccess)
            {
                return View(noteResult.Data);
            }

            return RedirectToAction("Index", "Home");
        }

    }
}

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Website</title>

    <link href="~/css/adminlte.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Website.styles.css" asp-append-version="true" />
    <link href="~/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link">@ViewBag.Title</a>
                </li>

            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->


                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Account/Logout" role="button">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="/" class="brand-link">
                <img src="~/img/logo.webp" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">
                    Notes Manager
                </span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/img/user.png" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">@User.Identity.Name</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Notes
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Notes" asp-action="Index" class="nav-link active">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>My Notes</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Notes" asp-action="Manage" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Add Note</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <main role="main" class="pb-3 m-2">
                @RenderBody()
            </main>
        </div>
    </div>


    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/adminlte.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <partial name="_ValidationScriptsPartial" />
</body>
</html>

Website/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Website</title>

    <link href="~/css/adminlte.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Website.styles.css" asp-append-version="true" />
    <link href="~/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />
</head>
<body>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/adminlte.min.js"></script>

    <partial name="_ValidationScriptsPartial" />
</body>
</html>